theme: jekyll-theme-cayman
title: Integracio-AOC-SOAPUI
description: Projecte SOAPUI amb peticions d'exemple de les diferents modalitats de consum dels serveis web del consorci AOC.
markdown: GFM
plugins:
  - jemoji
